import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, ChevronDown, Menu, ShieldCheck, Sparkles, X } from 'lucide-react';
import './styles.css';

const services=[
 {title:'Deep Interior Detail',price:'From $179',copy:'A full interior reset with vacuuming, steam cleaning, stain treatment, plastics, glass and finishing touches.'},
 {title:'Full Detail',price:'From $249',copy:'A complete inside-and-out transformation for vehicles that need more than a quick tidy-up.'},
 {title:'Tradie Reset',price:'From $229',copy:'Built for work utes and vans carrying dust, mud, stains and the realities of a hard week on site.'},
 {title:'Headlight Restoration',price:'Quoted per vehicle',copy:'Restore clarity, improve appearance and help tired headlights look sharp again.'}
];
const faqs=[
 ['Do you come to me?','Apex operates as a mobile and semi-mobile service across Napier, Hastings and wider Hawke’s Bay. Access to power, water and a safe work area may be required depending on the job.'],
 ['Are the advertised prices fixed?','Packages are priced from the advertised amount. Final quotes reflect vehicle size, condition, pet hair, stains, access and the total work required.'],
 ['How long does a detail take?','Most deep interior and full details take several hours. Heavily soiled vehicles, large SUVs, vans and seats-out work may take longer.'],
 ['Can you clean work vehicles and fleets?','Yes. Tradie utes, work vans and business fleets are a core growth area for Apex, with repeat maintenance options available.']
];

function App(){
 const [open,setOpen]=useState(false); const [faq,setFaq]=useState(0);
 const submit=(e)=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nVehicle: ${d.get('vehicle')}\nService: ${d.get('service')}\nLocation: ${d.get('location')}\n\nDetails:\n${d.get('details')}`;location.href=`mailto:bookings@apexdetailers.co.nz?subject=${encodeURIComponent('Apex website enquiry')}&body=${encodeURIComponent(body)}`};
 return <>
 <header><div className="wrap nav"><a className="brand" href="#top"><span className="mark">A</span><span><b>APEX</b><small>DETAILERS</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['services','process','about','faq','contact'].map(x=><a key={x} href={`#${x}`} onClick={()=>setOpen(false)}>{x}</a>)}<a className="navCta" href="#contact">Get a quote</a></nav></div></header>
 <main id="top">
 <section className="hero"><div className="glow"/><div className="wrap heroGrid"><div><p className="eyebrow">Napier · Hastings · Hawke’s Bay</p><h1>Vehicle detailing with an <em>unfair level of care.</em></h1><p className="lead">Premium interior and exterior detailing for daily drivers, family vehicles, tradie utes and fleets.</p><div className="actions"><a className="btn yellow" href="#contact">Request a quote <ArrowRight size={18}/></a><a className="textLink" href="#services">Explore services</a></div><div className="proof"><span><ShieldCheck/>Careful vehicle handling</span><span><Sparkles/>Detail-focused finishes</span></div></div><div className="heroCard"><div className="ring"><div className="heroA">A</div></div><p>PRECISION.</p><p>PROTECTION.</p><p>PERFECTION.</p></div></div></section>
 <section id="services" className="section"><div className="wrap"><p className="eyebrow dark">Services</p><div className="heading"><h2>Built for real vehicles, not showroom fantasies.</h2><p>Every job starts with the actual condition of your vehicle. We quote honestly, communicate clearly and focus on the work that will make the biggest difference.</p></div><div className="cards">{services.map((s,i)=><article key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><b>{s.price}</b><p>{s.copy}</p><a href="#contact">Request quote <ArrowRight size={16}/></a></article>)}</div><p className="fine">Prices are starting points. Vehicle size, condition and required labour affect the final quote.</p></div></section>
 <section id="process" className="section process"><div className="wrap"><p className="eyebrow">The Apex process</p><h2>Clear from quote to handover.</h2><div className="steps">{[['01','Send the details','Tell us the vehicle, service, location and current condition.'],['02','Receive your quote','We confirm scope, starting price and any condition-based adjustments.'],['03','Detail day','Your vehicle is treated methodically using the right process for each surface.'],['04','Final inspection','We check the finish, walk you through the result and recommend sensible aftercare.']].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 <section id="about" className="section about"><div className="wrap aboutGrid"><div className="aboutVisual"><div className="bigA">A</div></div><div><p className="eyebrow dark">Why Apex</p><h2>A local service built around pride in the result.</h2><p>Apex Detailers serves Hawke’s Bay with a practical, premium approach to vehicle care. The goal is simple: make every customer feel their vehicle was genuinely looked after.</p><ul>{['Clear quotes with no vague promises','Methods suited to the vehicle and material','Realistic results explained honestly','Built for repeat customers and business fleets'].map(x=><li key={x}><Check/> {x}</li>)}</ul></div></div></section>
 <section className="section commercial"><div className="wrap commercialGrid"><div><p className="eyebrow">Tradies & fleets</p><h2>Keep work vehicles presentable without losing a day.</h2></div><div><p>From one hard-working ute to a growing fleet, Apex can build a practical cleaning rhythm around your business.</p><a className="btn yellow" href="#contact">Discuss a fleet plan <ArrowRight size={18}/></a></div></div></section>
 <section id="faq" className="section"><div className="wrap faqGrid"><div><p className="eyebrow dark">Common questions</p><h2>Know what to expect before we start.</h2></div><div>{faqs.map((x,i)=><button className="faq" key={x[0]} onClick={()=>setFaq(faq===i?-1:i)}><span><b>{x[0]}</b><ChevronDown className={faq===i?'turn':''}/></span>{faq===i&&<p>{x[1]}</p>}</button>)}</div></div></section>
 <section id="contact" className="section contact"><div className="wrap contactGrid"><div><p className="eyebrow">Get a quote</p><h2>Tell us what your vehicle needs.</h2><p>Send the details below and your email app will open with everything ready to send.</p><a href="mailto:bookings@apexdetailers.co.nz">bookings@apexdetailers.co.nz</a></div><form onSubmit={submit}><div className="row"><input name="name" required placeholder="Your name"/><input name="phone" required placeholder="Phone number"/></div><div className="row"><input name="vehicle" required placeholder="Vehicle make and model"/><input name="location" required placeholder="Your suburb / location"/></div><select name="service" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}</select><textarea name="details" rows="5" placeholder="Condition, stains, pet hair, access, preferred timing or anything else we should know"/><button className="btn yellow" type="submit">Prepare enquiry <ArrowRight size={18}/></button></form></div></section>
 </main><footer><div className="wrap foot"><div className="brand"><span className="mark">A</span><span><b>APEX</b><small>DETAILERS</small></span></div><p>Premium vehicle detailing across Hawke’s Bay.</p><p>© {new Date().getFullYear()} Apex Detailers</p></div></footer>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
