import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{addDoc,collection,getDocs,serverTimestamp}from"firebase/firestore";
import{onAuthStateChanged,signInWithEmailAndPassword,signOut}from"firebase/auth";
import{auth,db}from"./firebase";
import"./data-tools.css";

const ownerUids=(import.meta.env.VITE_APEX_OWNER_UIDS||"fnc4G85CtmQVy0OooOzfOoSC9u22,FqDrn1aPFHXUB5ogb2rN9D7mRG42").split(",").map(v=>v.trim());
const clean=v=>String(v??"").trim();
const normal=v=>clean(v).toLowerCase().replace(/\s+/g," ");
const customerKey=c=>[normal(c.email),normal(c.phone),normal(c.businessName||`${c.firstName||""} ${c.lastName||""}`)].join("|");
const download=(name,data)=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
const serialise=value=>{if(value?.toDate)return value.toDate().toISOString();if(Array.isArray(value))return value.map(serialise);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,serialise(v)]));return value};

function App(){
 const[user,setUser]=useState(null),[ready,setReady]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[file,setFile]=useState(null);
 const owner=Boolean(user&&ownerUids.includes(user.uid));
 useEffect(()=>onAuthStateChanged(auth,next=>{if(next&&!ownerUids.includes(next.uid)){signOut(auth);setMessage("That account is not authorised for Apex HQ.");setUser(null)}else setUser(next);setReady(true)}),[]);
 async function login(e){e.preventDefault();setBusy(true);setMessage("");try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch{setMessage("Login failed. Check your Firebase email and password.")}setBusy(false)}
 async function backup(){setBusy(true);setMessage("Building backup…");try{const names=["customers","jobs","vouchers","bookingRequests","inquiries"];const data={exportedAt:new Date().toISOString(),version:1,collections:{}};for(const name of names){const snap=await getDocs(collection(db,name));data.collections[name]=snap.docs.map(d=>({id:d.id,...serialise(d.data())}))}download(`apex-hq-backup-${new Date().toISOString().slice(0,10)}.json`,data);setMessage("Full Apex HQ backup downloaded.")}catch(err){setMessage(err.message||"Backup failed.")}setBusy(false)}
 async function exportCustomers(){setBusy(true);try{const snap=await getDocs(collection(db,"customers"));download(`apex-customers-${new Date().toISOString().slice(0,10)}.json`,snap.docs.map(d=>({id:d.id,...serialise(d.data())})));setMessage("Customer export downloaded.")}catch(err){setMessage(err.message||"Export failed.")}setBusy(false)}
 async function importCustomers(){if(!file)return setMessage("Choose a JSON customer file first.");setBusy(true);setMessage("Checking customer file…");try{const parsed=JSON.parse(await file.text());const rows=Array.isArray(parsed)?parsed:(parsed.customers||parsed.collections?.customers||[]);if(!Array.isArray(rows)||!rows.length)throw new Error("No customers were found in that JSON file.");const existingSnap=await getDocs(collection(db,"customers"));const keys=new Set(existingSnap.docs.map(d=>customerKey(d.data())));let added=0,skipped=0;for(const raw of rows){const row={firstName:clean(raw.firstName),lastName:clean(raw.lastName),businessName:clean(raw.businessName),phone:clean(raw.phone),email:clean(raw.email).toLowerCase(),address:clean(raw.address),area:clean(raw.area),preferredContact:clean(raw.preferredContact)||"text",customerType:clean(raw.customerType)||"standard",notes:clean(raw.notes)};if(!row.firstName&&!row.lastName&&!row.businessName){skipped++;continue}const key=customerKey(row);if(keys.has(key)){skipped++;continue}await addDoc(collection(db,"customers"),{...row,ownerUid:user.uid,importedAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});keys.add(key);added++}setMessage(`Import complete: ${added} added, ${skipped} skipped as duplicate or incomplete.`)}catch(err){setMessage(err.message||"Import failed.")}setBusy(false)}
 if(!ready)return <main className="page"><section><h1>Apex HQ Data Tools</h1><p>Loading…</p></section></main>;
 if(!owner)return <main className="page"><form onSubmit={login}><span>PRIVATE OWNER TOOL</span><h1>Apex HQ Data Tools</h1><p>Export backups and safely import customer JSON files.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<div className="notice">{message}</div>}</form></main>;
 return <main className="page"><header><div><span>APEX HQ</span><h1>Data Tools</h1></div><div><a href="/hq">← Back to HQ</a><button className="secondary" onClick={()=>signOut(auth)}>Sign out</button></div></header><section className="grid"><article><h2>Full business backup</h2><p>Downloads customers, jobs, vouchers, booking requests and inquiries into one dated JSON file.</p><button disabled={busy} onClick={backup}>Download full backup</button></article><article><h2>Customer export</h2><p>Downloads only the customer database for a lighter contact backup.</p><button disabled={busy} onClick={exportCustomers}>Download customers</button></article><article><h2>Import customers</h2><p>Accepts a customer array, a <code>customers</code> array, or an Apex backup. Existing email/phone/name matches are skipped.</p><input type="file" accept="application/json,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={busy||!file} onClick={importCustomers}>Import customer file</button></article></section>{message&&<div className="notice fixed">{message}</div>}<footer>Run a full backup before every large import or production deployment.</footer></main>
}
createRoot(document.getElementById("root")).render(<App/>);
