import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{addDoc,collection,doc,getDocs,onSnapshot,serverTimestamp,setDoc}from"firebase/firestore";
import{GoogleAuthProvider,onAuthStateChanged,signInWithEmailAndPassword,signInWithPopup,signOut}from"firebase/auth";
import{auth,db}from"./firebase";
import{approveBookingRequest,createManualBooking,declineBookingRequest,getGoogleCalendarStatus,startGoogleCalendarConnect,syncJobToCalendar}from"./apex-api";
import{defaultBookingSettings,formatDate,money,servicePackages,vehicleTypes}from"./booking-data";
import{disableDeviceLock,hasBiometricLock,hasPinLock,isDeviceLockEnabled,isSessionUnlocked,lockSession,markSessionUnlocked,registerBiometricLock,setPin,supportsBiometrics,verifyBiometricLock,verifyPin}from"./device-lock";
import"./hq-v5.css";

const ownerUids=(import.meta.env.VITE_APEX_OWNER_UIDS||"fnc4G85CtmQVy0OooOzfOoSC9u22,FqDrn1aPFHXUB5ogb2rN9D7mRG42,maefd5cQ9qcIKSeU4b3yZKUL8UW2").split(",").map(v=>v.trim());
const nav=[["dashboard","Command","âŒ‚"],["inbox","Inbox","â†§"],["calendar","Calendar","â—·"],["jobs","Jobs","â—†"],["customers","Customers","â—Ž"],["settings","Settings","âš™"]];
const statusList=["Quote Sent","Booked","Confirmed","In Progress","Completed","Prepare Hnry Invoice","Invoice Sent","Paid","Review Request Sent","Archived"];
const blankBooking={customerName:"",phone:"",email:"",address:"",area:"Napier",vehicleYear:"",vehicleMake:"",vehicleModel:"",rego:"",vehicleType:"small",serviceId:"deep",bookingDate:"",bookingTime:"08:30",notes:"",overrideConflict:false};
const blankCustomer={firstName:"",lastName:"",businessName:"",phone:"",email:"",address:"",area:"Napier",preferredContact:"text",customerType:"standard",notes:""};
const nameOf=c=>c.businessName||[c.firstName,c.lastName].filter(Boolean).join(" ")||c.customerName||"Unnamed";
const clean=v=>String(v??"").trim();
const normal=v=>clean(v).toLowerCase().replace(/\s+/g," ");
const customerKey=c=>[normal(c.email),normal(c.phone),normal(c.businessName||`${c.firstName||""} ${c.lastName||""}`)].join("|");

function Brand(){return <div className="hqBrand"><img src="/assets/apex-logo-official.svg" alt="Apex Detailers"/><div><strong>APEX DETAILERS</strong><span>HQ / V5</span></div></div>}
function Login({busy,error,onEmail,onGoogle}){const[email,setEmail]=useState(""),[password,setPassword]=useState("");return <main className="loginPage"><section><Brand/><span className="eyebrow">PRIVATE OPERATIONS</span><h1>The business command centre.</h1><p>Customers, jobs, bookings and business records in one clean mobile HQ.</p></section><form onSubmit={e=>{e.preventDefault();onEmail(email,password)}}><h2>Sign in</h2><button type="button" className="google" onClick={onGoogle}>Continue with Google</button><div className="or">or</div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="alert">{error}</div>}<button disabled={busy}>{busy?"Signing inâ€¦":"Enter Apex HQ"}</button><p className="muted">After the first secure sign-in, Face ID can unlock Apex HQ on this iPhone.</p></form></main>}
function Gate({unlock,logout}){const[pin,setPinValue]=useState(""),[error,setError]=useState("");async function face(){try{if(await verifyBiometricLock()){markSessionUnlocked();unlock()}}catch{setError("Face ID was cancelled or unavailable. Use your PIN or sign in again.")}}async function submit(e){e.preventDefault();if(await verifyPin(pin)){markSessionUnlocked();unlock()}else setError("That PIN is not correct.")}return <main className="gate"><section><Brand/><span className="eyebrow">APEX HQ LOCKED</span><h1>Welcome back, Brad.</h1>{hasBiometricLock()&&<button onClick={face}>Unlock with Face ID</button>}{hasPinLock()&&<form onSubmit={submit}><input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPinValue(e.target.value.replace(/\D/g,""))} placeholder="6-digit PIN"/><button>Unlock with PIN</button></form>}{error&&<div className="alert">{error}</div>}<button className="text" onClick={logout}>Sign out completely</button></section></main>}
function Modal({title,close,children}){return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><header><h2>{title}</h2><button onClick={close}>Ã—</button></header>{children}</section></div>}
function ManualBooking({close,save,busy}){const[form,setForm]=useState(blankBooking),update=(k,v)=>setForm(o=>({...o,[k]:v}));return <Modal title="Add confirmed booking" close={close}><form className="modalForm" onSubmit={e=>{e.preventDefault();save(form)}}><div className="formGrid"><label>Customer<input required value={form.customerName} onChange={e=>update("customerName",e.target.value)}/></label><label>Mobile<input required value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label>Area<input required value={form.area} onChange={e=>update("area",e.target.value)}/></label><label className="wide">Address<input required value={form.address} onChange={e=>update("address",e.target.value)}/></label><label>Year<input value={form.vehicleYear} onChange={e=>update("vehicleYear",e.target.value)}/></label><label>Make<input required value={form.vehicleMake} onChange={e=>update("vehicleMake",e.target.value)}/></label><label>Model<input required value={form.vehicleModel} onChange={e=>update("vehicleModel",e.target.value)}/></label><label>Rego<input value={form.rego} onChange={e=>update("rego",e.target.value.toUpperCase())}/></label><label>Vehicle<select value={form.vehicleType} onChange={e=>update("vehicleType",e.target.value)}>{vehicleTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Service<select value={form.serviceId} onChange={e=>update("serviceId",e.target.value)}>{servicePackages.map(s=><option key={s.id} value={s.id}>{s.name} â€” {money(s.price)}</option>)}</select></label><label>Date<input required type="date" value={form.bookingDate} onChange={e=>update("bookingDate",e.target.value)}/></label><label>Start<input required type="time" value={form.bookingTime} onChange={e=>update("bookingTime",e.target.value)}/></label><label className="wide">Notes<textarea rows="3" value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div><button disabled={busy}>{busy?"Creatingâ€¦":"Create booking"}</button></form></Modal>}
function CustomerModal({close,save,busy}){const[form,setForm]=useState(blankCustomer),update=(k,v)=>setForm(o=>({...o,[k]:v}));return <Modal title="Add customer" close={close}><form className="modalForm" onSubmit={e=>{e.preventDefault();save(form)}}><div className="formGrid"><label>First name<input value={form.firstName} onChange={e=>update("firstName",e.target.value)}/></label><label>Last name<input value={form.lastName} onChange={e=>update("lastName",e.target.value)}/></label><label className="wide">Business / fleet name<input value={form.businessName} onChange={e=>update("businessName",e.target.value)}/></label><label>Mobile<input value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label className="wide">Address<input value={form.address} onChange={e=>update("address",e.target.value)}/></label><label>Area<input value={form.area} onChange={e=>update("area",e.target.value)}/></label><label>Customer type<select value={form.customerType} onChange={e=>update("customerType",e.target.value)}><option value="standard">Standard</option><option value="friend">Friend</option><option value="family">Family</option><option value="fleet">Fleet / commercial</option></select></label><label className="wide">Notes<textarea rows="4" value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div><button disabled={busy}>{busy?"Savingâ€¦":"Save customer"}</button></form></Modal>}

function parseCsv(text){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const split=line=>{const out=[];let cur="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out};const headers=split(lines[0]).map(h=>normal(h).replace(/[^a-z0-9]/g,""));return lines.slice(1).map(line=>Object.fromEntries(headers.map((h,i)=>[h,split(line)[i]||""])))}
function mapCustomer(raw){const full=clean(raw.name||raw.fullname||raw.customername);const parts=full.split(/\s+/).filter(Boolean);return{firstName:clean(raw.firstName||raw.firstname||(parts.length?parts[0]:"")),lastName:clean(raw.lastName||raw.lastname||(parts.length>1?parts.slice(1).join(" "):"")),businessName:clean(raw.businessName||raw.businessname||raw.company),phone:clean(raw.phone||raw.mobile||raw.telephone),email:clean(raw.email).toLowerCase(),address:clean(raw.address||raw.street),area:clean(raw.area||raw.suburb||raw.city)||"Napier",preferredContact:clean(raw.preferredContact||raw.preferredcontact)||"text",customerType:clean(raw.customerType||raw.customertype)||"standard",notes:clean(raw.notes||raw.note)}}

function App(){
 const[user,setUser]=useState(null),[ready,setReady]=useState(false),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(""),[unlocked,setUnlocked]=useState(!isDeviceLockEnabled()||isSessionUnlocked()),[tab,setTab]=useState("dashboard"),[customers,setCustomers]=useState([]),[jobs,setJobs]=useState([]),[requests,setRequests]=useState([]),[inquiries,setInquiries]=useState([]),[settings,setSettings]=useState(defaultBookingSettings),[calendar,setCalendar]=useState({connected:false}),[manual,setManual]=useState(false),[customerModal,setCustomerModal]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
 const owner=Boolean(user&&ownerUids.includes(user.uid));
 useEffect(()=>onAuthStateChanged(auth,next=>{if(next&&!ownerUids.includes(next.uid)){signOut(auth);setAuthError("That account is not authorised for Apex HQ.");setUser(null)}else setUser(next);setUnlocked(Boolean(next)&&(!isDeviceLockEnabled()||isSessionUnlocked()));setReady(true)}),[]);
 useEffect(()=>{if(!owner)return;const stops=[onSnapshot(collection(db,"customers"),s=>setCustomers(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"jobs"),s=>setJobs(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"bookingRequests"),s=>setRequests(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"inquiries"),s=>setInquiries(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(doc(db,"settings","booking"),s=>s.exists()&&setSettings({...defaultBookingSettings,...s.data()}))];getGoogleCalendarStatus().then(setCalendar).catch(()=>{});return()=>stops.forEach(stop=>stop())},[owner]);
 const notify=message=>{setToast(message);setTimeout(()=>setToast(""),3500)};
 async function emailLogin(email,password){setAuthBusy(true);setAuthError("");try{await signInWithEmailAndPassword(auth,email,password)}catch{setAuthError("Login failed. Check your email and password.")}setAuthBusy(false)}
 async function googleLogin(){setAuthBusy(true);setAuthError("");try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(err){setAuthError(err.code==="auth/operation-not-allowed"?"Google login is not enabled in Firebase Authentication yet.":err.message||"Google sign-in failed.")}setAuthBusy(false)}
 async function logout(){lockSession();await signOut(auth)}
 async function approve(item){setBusy(true);try{await approveBookingRequest({requestId:item.id});notify("Booking confirmed, Calendar synced and emails sent.")}catch(err){notify(err.message||"Could not approve booking.")}setBusy(false)}
 async function decline(item){if(!confirm(`Decline ${item.customerName}'s request?`))return;setBusy(true);try{await declineBookingRequest({requestId:item.id});notify("Request declined.")}catch(err){notify(err.message||"Could not decline request.")}setBusy(false)}
 async function saveManual(form){setBusy(true);try{await createManualBooking(form);setManual(false);setTab("calendar");notify("Booking created.")}catch(err){notify(err.message||"Cloud booking tools are paused right now.")}setBusy(false)}
 async function saveCustomer(form){if(!clean(form.firstName)&&!clean(form.lastName)&&!clean(form.businessName))return notify("Add a customer or business name.");setBusy(true);try{await addDoc(collection(db,"customers"),{...form,email:clean(form.email).toLowerCase(),ownerUid:user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setCustomerModal(false);setTab("customers");notify("Customer added.")}catch(err){notify(err.message||"Could not save customer.")}setBusy(false)}
 async function importCustomers(file){if(!file)return;setBusy(true);try{const text=await file.text();let rows;if(file.name.toLowerCase().endsWith(".csv"))rows=parseCsv(text);else{const parsed=JSON.parse(text);rows=Array.isArray(parsed)?parsed:(parsed.customers||parsed.collections?.customers||[])}if(!Array.isArray(rows)||!rows.length)throw new Error("No customer rows found.");const existing=await getDocs(collection(db,"customers"));const keys=new Set(existing.docs.map(d=>customerKey(d.data())));let added=0,skipped=0;for(const raw of rows){const row=mapCustomer(raw);if(!row.firstName&&!row.lastName&&!row.businessName){skipped++;continue}const key=customerKey(row);if(keys.has(key)){skipped++;continue}await addDoc(collection(db,"customers"),{...row,ownerUid:user.uid,importedAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});keys.add(key);added++}notify(`${added} customers imported, ${skipped} skipped.`)}catch(err){notify(err.message||"Customer import failed.")}setBusy(false)}
 const today=new Date().toLocaleDateString("en-CA",{timeZone:"Pacific/Auckland"});const pending=requests.filter(r=>r.status==="pending"),newInquiries=inquiries.filter(i=>i.status==="new");const upcoming=jobs.filter(j=>j.bookingDate>=today&&!['Archived','Cancelled'].includes(j.status)).sort((a,b)=>`${a.bookingDate}${a.bookingTime}`.localeCompare(`${b.bookingDate}${b.bookingTime}`));const paid=jobs.reduce((sum,j)=>sum+(["Paid","Review Request Sent"].includes(j.status)?Number(j.paidAmount||j.total||0):0),0);
 if(!ready)return <main className="boot"><Brand/>Loadingâ€¦</main>;if(!owner)return <Login busy={authBusy} error={authError} onEmail={emailLogin} onGoogle={googleLogin}/>;if(isDeviceLockEnabled()&&!unlocked)return <Gate unlock={()=>setUnlocked(true)} logout={logout}/>;
 return <div className="shell"><aside><Brand/><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i>{label}{id==="inbox"&&(pending.length+newInquiries.length)>0&&<em>{pending.length+newInquiries.length}</em>}</button>)}</nav><footer><button onClick={()=>{lockSession();setUnlocked(false)}}>âŒ¾ Lock HQ</button><button onClick={logout}>â†’ Sign out</button></footer></aside><div className="workspace"><header className="top"><div><span className="eyebrow">APEX HQ Â· {new Date().toLocaleDateString("en-NZ",{weekday:"long",day:"numeric",month:"long"}).toUpperCase()}</span><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div>{tab==="customers"&&<button className="secondaryTop" onClick={()=>setCustomerModal(true)}>ï¼‹ Customer</button>}<button onClick={()=>setManual(true)}>ï¼‹ Booking</button></div></header><main>
 {tab==="dashboard"&&<><section className="command"><div><span className="eyebrow">TODAY'S COMMAND DECK</span><h2>{upcoming.filter(j=>j.bookingDate===today).length?`${upcoming.filter(j=>j.bookingDate===today).length} vehicle${upcoming.filter(j=>j.bookingDate===today).length===1?"":"s"} on today.`:"The day is clear. Let's fill it properly."}</h2><p>{pending.length} booking request{pending.length===1?"":"s"} and {newInquiries.length} inquir{newInquiries.length===1?"y":"ies"} waiting.</p><div className="heroActions"><button onClick={()=>setManual(true)}>ï¼‹ Add booking</button><button className="secondaryTop" onClick={()=>setCustomerModal(true)}>ï¼‹ Add customer</button></div></div><article><span className="eyebrow">NEXT UP</span>{upcoming[0]?<><b>{formatDate(upcoming[0].bookingDate)} Â· {upcoming[0].bookingTime}</b><h3>{upcoming[0].customerName}</h3><p>{upcoming[0].vehicle}</p></>:<h3>No upcoming booking.</h3>}</article></section><section className="stats"><Stat label="Pending bookings" value={pending.length}/><Stat label="New inquiries" value={newInquiries.length}/><Stat label="Paid revenue" value={money(paid)}/><Stat label="Customers" value={customers.length}/></section><Panel title="Coming up">{upcoming.slice(0,6).map(j=><Agenda key={j.id} job={j}/>)}</Panel></>}
 {tab==="inbox"&&<><Intro title="Inbox" text="Booking requests and enquiries arrive here."/><div className="cards">{pending.map(r=><article className="request" key={r.id}><header><div><h3>{r.customerName}</h3><span>{r.email} Â· {r.phone}</span></div><b>{formatDate(r.bookingDate)}<small>{r.bookingTime}</small></b></header><p>{r.vehicle||[r.vehicleYear,r.vehicleMake,r.vehicleModel].filter(Boolean).join(" ")} Â· {r.serviceName}</p><p>{r.address}, {r.area}</p>{r.notes&&<blockquote>{r.notes}</blockquote>}<footer><button onClick={()=>approve(r)} disabled={busy}>Confirm</button><button className="danger" onClick={()=>decline(r)} disabled={busy}>Decline</button></footer></article>)}{newInquiries.map(i=><article className="request inquiry" key={i.id}><header><div><h3>{i.name}</h3><span>{i.email} Â· {i.phone}</span></div><b>INQUIRY</b></header><blockquote>{i.message}</blockquote><footer><button onClick={()=>setDoc(doc(db,"inquiries",i.id),{status:"resolved"},{merge:true})}>Mark resolved</button></footer></article>)}</div>{!pending.length&&!newInquiries.length&&<Empty text="Nothing waiting in the inbox."/>}</>}
 {tab==="calendar"&&<><Intro title="Schedule" text="Confirmed Apex jobs and dates."/><div className="calendar">{upcoming.map(j=><Agenda key={j.id} job={j} sync={async()=>{try{await syncJobToCalendar({jobId:j.id});notify("Calendar event synced.")}catch{notify("Calendar sync is paused right now.")}}}/>)}</div>{!upcoming.length&&<Empty text="No upcoming bookings."/>}</>}
 {tab==="jobs"&&<><Intro title="Jobs" text="Quotes, booked work, completed details, Hnry handoff and paid status."/><div className="table">{[...jobs].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(j=><div className="job" key={j.id}><i>â—†</i><div><b>{j.customerName}</b><span>{j.vehicle}</span></div><div><b>{j.packageName}</b><span>{j.bookingDate?`${formatDate(j.bookingDate)} Â· ${j.bookingTime}`:"No booking date"}</span></div><strong>{money(j.total)}</strong><select value={j.status||"Booked"} onChange={e=>setDoc(doc(db,"jobs",j.id),{status:e.target.value},{merge:true})}>{statusList.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>{!jobs.length&&<Empty text="No jobs saved yet."/>}</>}
 {tab==="customers"&&<><div className="sectionLead"><Intro title="Customers" text="Contact details, vehicles and repeat-work history."/><div className="customerActions"><button onClick={()=>setCustomerModal(true)}>ï¼‹ Add customer</button><label className="importButton">Import JSON or CSV<input type="file" accept=".json,.csv,application/json,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)importCustomers(f);e.target.value=""}}/></label></div></div><div className="customerGrid">{customers.map(c=>{const history=jobs.filter(j=>j.customerId===c.id);return <article key={c.id}><header><i>{nameOf(c).slice(0,1)}</i><div><h3>{nameOf(c)}</h3><span>{c.phone||"No phone"}{c.email?` Â· ${c.email}`:""}</span></div></header><p>{c.address||c.area||"No address saved"}</p><p>{c.lastVehicle||history[0]?.vehicle||"No vehicle saved"}</p><footer><b>{history.length} jobs</b><b>{money(history.reduce((sum,j)=>sum+Number(j.total||0),0))}</b></footer></article>})}</div>{!customers.length&&<Empty text="Add your first customer manually or import a JSON/CSV file."/>}</>}
 {tab==="settings"&&<Settings user={user} settings={settings} setSettings={setSettings} calendar={calendar} setCalendar={setCalendar} notify={notify}/>} 
 </main></div><nav className="mobile">{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i><small>{label}</small></button>)}</nav>{manual&&<ManualBooking close={()=>setManual(false)} save={saveManual} busy={busy}/>} {customerModal&&<CustomerModal close={()=>setCustomerModal(false)} save={saveCustomer} busy={busy}/>} {toast&&<div className="toast">{toast}</div>}</div>}
function Stat({label,value}){return <article><span>{label}</span><b>{value}</b></article>}function Intro({title,text}){return <header className="intro"><span className="eyebrow">APEX OPERATIONS</span><h2>{title}</h2><p>{text}</p></header>}function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}function Agenda({job,sync}){return <div className="agenda"><time><b>{new Date(`${job.bookingDate}T00:00:00`).getDate()}</b><span>{new Date(`${job.bookingDate}T00:00:00`).toLocaleDateString("en-NZ",{month:"short"})}</span></time><div><b>{job.customerName}</b><span>{job.vehicle} Â· {job.packageName}</span></div><em>{job.bookingTime}</em>{sync&&<button onClick={sync}>Sync</button>}</div>}function Empty({text}){return <div className="empty"><b>â†’</b><p>{text}</p></div>}
function Settings({user,settings,setSettings,calendar,setCalendar,notify}){const[pin,setPinValue]=useState("");async function save(){await setDoc(doc(db,"settings","booking"),settings,{merge:true});notify("Booking settings saved.")}async function connect(){try{const result=await startGoogleCalendarConnect();window.location.assign(result.url)}catch{notify("Calendar connection is paused right now.")}}return <><Intro title="Settings" text="Security, data tools and booking controls."/><div className="settings"><section><h3>Face ID unlock</h3><p className="muted">Face ID is the iPhone security check used by Safari. Apple may describe the underlying credential as a passkey during setup.</p>{supportsBiometrics()&&<button onClick={async()=>{try{await registerBiometricLock(user);notify("Face ID unlock enabled on this device.")}catch(err){notify(err.message||"Face ID setup failed.")}}}>{hasBiometricLock()?"Set up Face ID again":"Enable Face ID unlock"}</button>}<label>Backup PIN<input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPinValue(e.target.value.replace(/\D/g,""))}/></label><button className="secondary" onClick={async()=>{try{await setPin(pin);notify("Backup PIN enabled.")}catch(err){notify(err.message)}}}>Set backup PIN</button><button className="danger" onClick={()=>{disableDeviceLock();notify("Device lock removed.")}}>Remove device lock</button></section><section><h3>Data & customers</h3><p className="muted">Full backups and larger customer imports live in the dedicated owner tools page.</p><a className="settingsLink" href="/tools">Open backup & import tools â†’</a></section><section><h3>Online booking</h3><label className="check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Public booking page enabled</label><label>Minimum notice<input type="number" value={settings.minimumNoticeHours} onChange={e=>setSettings({...settings,minimumNoticeHours:Number(e.target.value)})}/></label><button onClick={save}>Save booking settings</button></section><section><h3>Google Calendar</h3><div className={`integration ${calendar.connected?"connected":""}`}><b>{calendar.connected?"Connected":"Paused / not connected"}</b><span>{calendar.email||"Calendar functions are currently paused."}</span></div><button onClick={connect}>Connect Calendar</button><button className="secondary" onClick={()=>getGoogleCalendarStatus().then(setCalendar).catch(()=>notify("Calendar functions are paused."))}>Refresh status</button></section></div></>}
createRoot(document.getElementById("root")).render(<App/>);
