import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{collection,doc,onSnapshot,setDoc}from"firebase/firestore";
import{GoogleAuthProvider,onAuthStateChanged,signInWithEmailAndPassword,signInWithPopup,signOut}from"firebase/auth";
import{auth,db}from"./firebase";
import{approveBookingRequest,createManualBooking,declineBookingRequest,getGoogleCalendarStatus,startGoogleCalendarConnect,syncJobToCalendar}from"./apex-api";
import{defaultBookingSettings,formatDate,money,servicePackages,vehicleTypes}from"./booking-data";
import{disableDeviceLock,hasBiometricLock,hasPinLock,isDeviceLockEnabled,isSessionUnlocked,lockSession,markSessionUnlocked,registerBiometricLock,setPin,supportsBiometrics,verifyBiometricLock,verifyPin}from"./device-lock";
import"./hq-v5.css";

const ownerUids=(import.meta.env.VITE_APEX_OWNER_UIDS||"fnc4G85CtmQVy0OooOzfOoSC9u22,FqDrn1aPFHXUB5ogb2rN9D7mRG42").split(",").map(v=>v.trim());
const nav=[["dashboard","Command","⌂"],["inbox","Inbox","↧"],["calendar","Calendar","◷"],["jobs","Jobs","◆"],["customers","Customers","◎"],["settings","Settings","⚙"]];
const statusList=["Quote Sent","Booked","Confirmed","In Progress","Completed","Prepare Hnry Invoice","Invoice Sent","Paid","Review Request Sent","Archived"];
const blankBooking={customerName:"",phone:"",email:"",address:"",area:"Napier",vehicleYear:"",vehicleMake:"",vehicleModel:"",rego:"",vehicleType:"small",serviceId:"deep",bookingDate:"",bookingTime:"08:30",notes:"",overrideConflict:false};
const nameOf=c=>c.businessName||[c.firstName,c.lastName].filter(Boolean).join(" ")||c.customerName||"Unnamed";

function Brand(){return <div className="hqBrand"><i/><div><strong>APEX DETAILERS</strong><span>HQ / V5</span></div></div>}

function Login({busy,error,onEmail,onGoogle}){
  const[email,setEmail]=useState(""),[password,setPassword]=useState("");
  return <main className="loginPage"><section><Brand/><span className="eyebrow">PRIVATE OPERATIONS</span><h1>The business command centre.</h1><p>Bookings, customers, jobs, Calendar and notifications in one sharp mobile HQ.</p></section><form onSubmit={e=>{e.preventDefault();onEmail(email,password)}}><h2>Sign in</h2><button type="button" className="google" onClick={onGoogle}>Continue with Google</button><div className="or">or</div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="alert">{error}</div>}<button disabled={busy}>{busy?"Signing in…":"Enter Apex HQ"}</button></form></main>
}

function Gate({unlock,logout}){
  const[pin,setPinValue]=useState(""),[error,setError]=useState("");
  async function bio(){try{if(await verifyBiometricLock()){markSessionUnlocked();unlock();}}catch{setError("Biometric unlock failed. Use the PIN or sign in again.")}}
  async function submit(e){e.preventDefault();if(await verifyPin(pin)){markSessionUnlocked();unlock()}else setError("That PIN is not correct.")}
  return <main className="gate"><section><Brand/><span className="eyebrow">DEVICE LOCKED</span><h1>Welcome back, Brad.</h1>{hasBiometricLock()&&<button onClick={bio}>Use Face ID / fingerprint</button>}{hasPinLock()&&<form onSubmit={submit}><input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPinValue(e.target.value.replace(/\D/g,""))} placeholder="6-digit PIN"/><button>Unlock with PIN</button></form>}{error&&<div className="alert">{error}</div>}<button className="text" onClick={logout}>Sign out completely</button></section></main>
}

function Modal({title,close,children}){return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</section></div>}

function Manual({close,save,busy}){
  const[form,setForm]=useState(blankBooking),update=(k,v)=>setForm(o=>({...o,[k]:v}));
  return <Modal title="Add confirmed booking" close={close}><form className="modalForm" onSubmit={e=>{e.preventDefault();save(form)}}><div className="formGrid"><label>Customer<input required value={form.customerName} onChange={e=>update("customerName",e.target.value)}/></label><label>Mobile<input required value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>Email for confirmation<input required type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label>Area<input required value={form.area} onChange={e=>update("area",e.target.value)}/></label><label className="wide">Address<input required value={form.address} onChange={e=>update("address",e.target.value)}/></label><label>Year<input value={form.vehicleYear} onChange={e=>update("vehicleYear",e.target.value)}/></label><label>Make<input required value={form.vehicleMake} onChange={e=>update("vehicleMake",e.target.value)}/></label><label>Model<input required value={form.vehicleModel} onChange={e=>update("vehicleModel",e.target.value)}/></label><label>Rego<input value={form.rego} onChange={e=>update("rego",e.target.value.toUpperCase())}/></label><label>Vehicle<select value={form.vehicleType} onChange={e=>update("vehicleType",e.target.value)}>{vehicleTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Service<select value={form.serviceId} onChange={e=>update("serviceId",e.target.value)}>{servicePackages.map(s=><option key={s.id} value={s.id}>{s.name} — {money(s.price)}</option>)}</select></label><label>Date<input required type="date" value={form.bookingDate} onChange={e=>update("bookingDate",e.target.value)}/></label><label>Start<input required type="time" value={form.bookingTime} onChange={e=>update("bookingTime",e.target.value)}/></label><label className="check wide"><input type="checkbox" checked={form.overrideConflict} onChange={e=>update("overrideConflict",e.target.checked)}/>Allow an intentional Calendar conflict</label><label className="wide">Notes<textarea rows="3" value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div><button disabled={busy}>{busy?"Creating…":"Create booking + Calendar event"}</button></form></Modal>
}

function App(){
  const[user,setUser]=useState(null),[ready,setReady]=useState(false),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(""),[unlocked,setUnlocked]=useState(!isDeviceLockEnabled()||isSessionUnlocked()),[tab,setTab]=useState("dashboard"),[customers,setCustomers]=useState([]),[jobs,setJobs]=useState([]),[requests,setRequests]=useState([]),[inquiries,setInquiries]=useState([]),[settings,setSettings]=useState(defaultBookingSettings),[calendar,setCalendar]=useState({connected:false}),[manual,setManual]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
  const owner=Boolean(user&&ownerUids.includes(user.uid));

  useEffect(()=>onAuthStateChanged(auth,next=>{if(next&&!ownerUids.includes(next.uid)){signOut(auth);setAuthError("That account is not authorised for Apex HQ.");setUser(null)}else setUser(next);setUnlocked(Boolean(next)&&(!isDeviceLockEnabled()||isSessionUnlocked()));setReady(true)}),[]);
  useEffect(()=>{if(!owner)return;const stops=[onSnapshot(collection(db,"customers"),s=>setCustomers(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"jobs"),s=>setJobs(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"bookingRequests"),s=>setRequests(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(collection(db,"inquiries"),s=>setInquiries(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(doc(db,"settings","booking"),s=>s.exists()&&setSettings({...defaultBookingSettings,...s.data()}))];getGoogleCalendarStatus().then(setCalendar).catch(()=>{});return()=>stops.forEach(stop=>stop())},[owner]);
  const notify=message=>{setToast(message);setTimeout(()=>setToast(""),3500)};

  async function emailLogin(email,password){setAuthBusy(true);setAuthError("");try{await signInWithEmailAndPassword(auth,email,password)}catch{setAuthError("Login failed. Check your email and password.")}setAuthBusy(false)}
  async function googleLogin(){setAuthBusy(true);setAuthError("");try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(err){setAuthError(err.message||"Google sign-in failed.")}setAuthBusy(false)}
  async function logout(){lockSession();await signOut(auth)}
  async function approve(item){setBusy(true);try{await approveBookingRequest({requestId:item.id});notify("Booking confirmed, Calendar synced and emails sent.")}catch(err){notify(err.message||"Could not approve booking.")}setBusy(false)}
  async function decline(item){if(!confirm(`Decline ${item.customerName}'s request?`))return;setBusy(true);try{await declineBookingRequest({requestId:item.id});notify("Request declined and the time released.")}catch(err){notify(err.message||"Could not decline request.")}setBusy(false)}
  async function saveManual(form){setBusy(true);try{await createManualBooking(form);setManual(false);setTab("calendar");notify("Booking created, Calendar synced and emails sent.")}catch(err){notify(err.message||"Could not create booking.")}setBusy(false)}

  const today=new Date().toLocaleDateString("en-CA",{timeZone:"Pacific/Auckland"});
  const pending=requests.filter(r=>r.status==="pending"),newInquiries=inquiries.filter(i=>i.status==="new");
  const upcoming=jobs.filter(j=>j.bookingDate>=today&&!['Archived','Cancelled'].includes(j.status)).sort((a,b)=>`${a.bookingDate}${a.bookingTime}`.localeCompare(`${b.bookingDate}${b.bookingTime}`));
  const paid=jobs.reduce((sum,j)=>sum+(["Paid","Review Request Sent"].includes(j.status)?Number(j.paidAmount||j.total||0):0),0);

  if(!ready)return <main className="boot"><Brand/>Loading…</main>;
  if(!owner)return <Login busy={authBusy} error={authError} onEmail={emailLogin} onGoogle={googleLogin}/>;
  if(isDeviceLockEnabled()&&!unlocked)return <Gate unlock={()=>setUnlocked(true)} logout={logout}/>;

  return <div className="shell"><aside><Brand/><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i>{label}{id==="inbox"&&(pending.length+newInquiries.length)>0&&<em>{pending.length+newInquiries.length}</em>}</button>)}</nav><footer><button onClick={()=>{lockSession();setUnlocked(false)}}>⌾ Lock device</button><button onClick={logout}>→ Sign out</button></footer></aside><div className="workspace"><header className="top"><div><span className="eyebrow">APEX HQ · {new Date().toLocaleDateString("en-NZ",{weekday:"long",day:"numeric",month:"long"}).toUpperCase()}</span><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div><a href="/book" target="_blank" rel="noreferrer">Open booking page ↗</a><button onClick={()=>setManual(true)}>＋ New booking</button></div></header><main>

    {tab==="dashboard"&&<><section className="command"><div><span className="eyebrow">TODAY'S COMMAND DECK</span><h2>{upcoming.filter(j=>j.bookingDate===today).length?`${upcoming.filter(j=>j.bookingDate===today).length} vehicle${upcoming.filter(j=>j.bookingDate===today).length===1?"":"s"} on today.`:"The day is clear. Let's fill it properly."}</h2><p>{pending.length} booking request{pending.length===1?"":"s"} and {newInquiries.length} inquir{newInquiries.length===1?"y":"ies"} in the inbox.</p><button onClick={()=>setManual(true)}>＋ Add booking</button></div><article><span className="eyebrow">NEXT UP</span>{upcoming[0]?<><b>{formatDate(upcoming[0].bookingDate)} · {upcoming[0].bookingTime}</b><h3>{upcoming[0].customerName}</h3><p>{upcoming[0].vehicle}</p></>:<h3>No upcoming booking.</h3>}</article></section><section className="stats"><Stat label="Pending bookings" value={pending.length}/><Stat label="New inquiries" value={newInquiries.length}/><Stat label="Paid revenue" value={money(paid)}/><Stat label="Customers" value={customers.length}/></section><Panel title="Coming up">{upcoming.slice(0,6).map(j=><Agenda key={j.id} job={j}/>)}</Panel></>}

    {tab==="inbox"&&<><Intro title="Inbox" text="Bookings and general enquiries arrive here. Booking emails go to the customer and Apex automatically."/><div className="cards">{pending.map(r=><article className="request" key={r.id}><header><div><h3>{r.customerName}</h3><span>{r.email} · {r.phone}</span></div><b>{formatDate(r.bookingDate)}<small>{r.bookingTime}</small></b></header><p>{r.vehicle||[r.vehicleYear,r.vehicleMake,r.vehicleModel].filter(Boolean).join(" ")} · {r.serviceName}</p><p>{r.address}, {r.area}</p>{r.notes&&<blockquote>{r.notes}</blockquote>}<footer><button onClick={()=>approve(r)} disabled={busy}>Confirm + sync</button><button className="danger" onClick={()=>decline(r)} disabled={busy}>Decline</button></footer></article>)}{newInquiries.map(i=><article className="request inquiry" key={i.id}><header><div><h3>{i.name}</h3><span>{i.email} · {i.phone}</span></div><b>INQUIRY</b></header><p>{i.subject||"Website inquiry"}</p><blockquote>{i.message}</blockquote><footer><button onClick={async()=>{await setDoc(doc(db,"inquiries",i.id),{status:"resolved"},{merge:true});notify("Inquiry marked resolved.")}}>Mark resolved</button></footer></article>)}</div>{!pending.length&&!newInquiries.length&&<Empty text="Nothing waiting in the inbox."/>}</>}

    {tab==="calendar"&&<><Intro title="Schedule" text="Apex HQ is the source of truth. Confirmed jobs are pushed to Google Calendar."/><div className="calendar">{upcoming.map(j=><Agenda key={j.id} job={j} sync={async()=>{try{await syncJobToCalendar({jobId:j.id});notify("Calendar event synced.")}catch(err){notify(err.message)}}}/>)}</div>{!upcoming.length&&<Empty text="No upcoming bookings."/>}</>}

    {tab==="jobs"&&<><Intro title="Jobs" text="Quotes, booked work, completed details, Hnry handoff and paid status."/><div className="table">{jobs.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(j=><div className="job" key={j.id}><i>◆</i><div><b>{j.customerName}</b><span>{j.vehicle}</span></div><div><b>{j.packageName}</b><span>{j.bookingDate?`${formatDate(j.bookingDate)} · ${j.bookingTime}`:"No booking date"}</span></div><strong>{money(j.total)}</strong><select value={j.status||"Booked"} onChange={async e=>{await setDoc(doc(db,"jobs",j.id),{status:e.target.value},{merge:true});notify(`Moved to ${e.target.value}.`)}}>{statusList.map(s=><option key={s}>{s}</option>)}</select></div>)}</div></>}

    {tab==="customers"&&<><Intro title="Customers" text="Contact details, vehicles and repeat-work history."/><div className="customerGrid">{customers.map(c=>{const history=jobs.filter(j=>j.customerId===c.id);return <article key={c.id}><header><i>{nameOf(c).slice(0,1)}</i><div><h3>{nameOf(c)}</h3><span>{c.phone} · {c.email}</span></div></header><p>{c.lastVehicle||history[0]?.vehicle||"No vehicle saved"}</p><footer><b>{history.length} jobs</b><b>{money(history.reduce((sum,j)=>sum+Number(j.total||0),0))}</b></footer></article>})}</div></>}

    {tab==="settings"&&<Settings user={user} settings={settings} setSettings={setSettings} calendar={calendar} setCalendar={setCalendar} notify={notify}/>} 
  </main></div><nav className="mobile">{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i><small>{label}</small></button>)}</nav>{manual&&<Manual close={()=>setManual(false)} save={saveManual} busy={busy}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Stat({label,value}){return <article><span>{label}</span><b>{value}</b></article>}
function Intro({title,text}){return <header className="intro"><span className="eyebrow">APEX OPERATIONS</span><h2>{title}</h2><p>{text}</p></header>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Agenda({job,sync}){return <div className="agenda"><time><b>{new Date(`${job.bookingDate}T00:00:00`).getDate()}</b><span>{new Date(`${job.bookingDate}T00:00:00`).toLocaleDateString("en-NZ",{month:"short"})}</span></time><div><b>{job.customerName}</b><span>{job.vehicle} · {job.packageName}</span></div><em>{job.bookingTime}</em>{sync&&<button onClick={sync}>Sync</button>}</div>}
function Empty({text}){return <div className="empty"><b>→</b><p>{text}</p></div>}

function Settings({user,settings,setSettings,calendar,setCalendar,notify}){
  const[pin,setPinValue]=useState("");
  async function save(){await setDoc(doc(db,"settings","booking"),settings,{merge:true});notify("Booking settings saved.")}
  async function connect(){try{const result=await startGoogleCalendarConnect();window.location.assign(result.url)}catch(err){notify(err.message||"Could not start Google connection.")}}
  return <><Intro title="Settings & integrations" text="Control booking hours, notifications, Google Calendar and the quick device lock."/><div className="settings"><section><h3>Online booking</h3><label className="check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Public booking page enabled</label><label>Minimum notice (hours)<input type="number" value={settings.minimumNoticeHours} onChange={e=>setSettings({...settings,minimumNoticeHours:Number(e.target.value)})}/></label><label>Booking window (days)<input type="number" value={settings.bookingWindowDays} onChange={e=>setSettings({...settings,bookingWindowDays:Number(e.target.value)})}/></label><label>Opening time<input type="time" value={settings.openingTime} onChange={e=>setSettings({...settings,openingTime:e.target.value})}/></label><label>Closing time<input type="time" value={settings.closingTime} onChange={e=>setSettings({...settings,closingTime:e.target.value})}/></label><label className="check"><input type="checkbox" checked={settings.customerEmails} onChange={e=>setSettings({...settings,customerEmails:e.target.checked})}/>Send customer booking emails</label><label className="check"><input type="checkbox" checked={settings.ownerEmails} onChange={e=>setSettings({...settings,ownerEmails:e.target.checked})}/>Send Apex owner alerts</label><button onClick={save}>Save booking settings</button></section><section><h3>Google Calendar + email</h3><div className={`integration ${calendar.connected?"connected":""}`}><b>{calendar.connected?"Connected":"Not connected"}</b><span>{calendar.email||"Connect the Google account used for Apex bookings."}</span></div><button onClick={connect}>{calendar.connected?"Reconnect Google":"Connect Google Calendar"}</button><button className="secondary" onClick={()=>getGoogleCalendarStatus().then(setCalendar)}>Refresh status</button><p className="muted">The same secure Google connection sends booking emails from Apex and blocks busy Calendar times.</p></section><section><h3>PIN or biometrics</h3><p className="muted">Firebase login remains the real security boundary. This is a quick lock for your own phone.</p><label>New 6-digit PIN<input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPinValue(e.target.value.replace(/\D/g,""))}/></label><button onClick={async()=>{try{await setPin(pin);notify("PIN lock enabled.")}catch(err){notify(err.message)}}}>Enable PIN</button>{supportsBiometrics()&&<button className="secondary" onClick={async()=>{try{await registerBiometricLock(user);notify("Biometric lock enabled.")}catch(err){notify(err.message)}}}>Enable Face ID / fingerprint</button>}<button className="danger" onClick={()=>{disableDeviceLock();notify("Device lock removed.")}}>Remove device lock</button></section></div></>
}

createRoot(document.getElementById("root")).render(<App/>);
